### ISSUE TITLE
经过dateFromMonthString 转换后的日期少一天

### ISSUE THREAD

**Issue by yupliang** [tiger8888/WHUCalendar#2]
WHUCalendarCal.m 中自定义了方法dateFromMonthString ，我在测试的时候发现
`
2016年7月01 --> 2016-06-30 16:00:00 +0000
`
而在用所得的2016-06-30 16:00:00 +0000 使用api （这个api我理解是求当前时间所在月份一共多少天）
`- (NSRange)rangeOfUnit:(NSCalendarUnit)smaller inUnit:(NSCalendarUnit)larger forDate:(NSDate *)date`
得到了结果
`
2016-06-30 16:00:00 +0000 has 31 days
`
看这两个结果的话实际上都是错的,希望大大多多赐教？

**Comment by tiger8888** [comment]
能提供个小demo嘛?  我估计2016-06-30 16:00:00 +0000 是UTC时间,而2016年7月01是本地时间
